const jobs = [
  // Technology & Software
  { title: "Software Engineer", count: 118420 },
  { title: "Software Developer", count: 105740 },
  { title: "Senior Software Engineer", count: 92480 },
  { title: "Junior Software Engineer", count: 73620 },
  { title: "Frontend Developer", count: 84260 },
  { title: "Frontend Engineer", count: 76840 },
  { title: "Backend Developer", count: 79430 },
  { title: "Backend Engineer", count: 73180 },
  { title: "Full Stack Developer", count: 82490 },
  { title: "Full Stack Engineer", count: 71640 },
  { title: "Web Developer", count: 91850 },
  { title: "Web Designer", count: 78420 },
  { title: "React Developer", count: 73420 },
  { title: "React Engineer", count: 68240 },
  { title: "Angular Developer", count: 67180 },
  { title: "Vue.js Developer", count: 63840 },
  { title: "JavaScript Developer", count: 68320 },
  { title: "TypeScript Developer", count: 64260 },
  { title: "Python Developer", count: 72180 },
  { title: "Java Developer", count: 81240 },
  { title: "C++ Developer", count: 68420 },
  { title: "C# Developer", count: 67280 },
  { title: "PHP Developer", count: 69420 },
  { title: "Ruby Developer", count: 61480 },
  { title: "Go Developer", count: 62340 },
  { title: "Mobile App Developer", count: 65740 },
  { title: "iOS Developer", count: 63820 },
  { title: "Android Developer", count: 68260 },
  { title: "Flutter Developer", count: 61740 },
  { title: "React Native Developer", count: 62840 },
  { title: "DevOps Engineer", count: 74860 },
  { title: "Cloud Engineer", count: 69240 },
  { title: "Cloud Architect", count: 61480 },
  { title: "Solutions Architect", count: 67320 },
  { title: "Software Architect", count: 64820 },
  { title: "Site Reliability Engineer", count: 62140 },
  { title: "Systems Engineer", count: 71980 },
  { title: "Systems Administrator", count: 68420 },
  { title: "Network Engineer", count: 76240 },
  { title: "Network Administrator", count: 63820 },
  { title: "Database Administrator", count: 67240 },
  { title: "Database Developer", count: 61480 },
  { title: "IT Support Specialist", count: 93420 },
  { title: "IT Support Technician", count: 78260 },
  { title: "Technical Support Specialist", count: 81420 },
  { title: "IT Manager", count: 74680 },
  { title: "IT Project Manager", count: 68240 },
  { title: "Information Security Analyst", count: 71360 },
  { title: "Cybersecurity Analyst", count: 69820 },
  { title: "Cybersecurity Engineer", count: 64180 },
  { title: "Security Engineer", count: 62740 },
  { title: "Penetration Tester", count: 60480 },
  { title: "QA Engineer", count: 67420 },
  { title: "QA Tester", count: 76280 },
  { title: "Software Test Engineer", count: 65140 },
  { title: "Automation Engineer", count: 61820 },
  { title: "Machine Learning Engineer", count: 68460 },
  { title: "AI Engineer", count: 72140 },
  { title: "Data Engineer", count: 74620 },
  { title: "Data Scientist", count: 79840 },
  { title: "Data Analyst", count: 81560 },
  { title: "Business Intelligence Analyst", count: 67480 },
  { title: "BI Developer", count: 61240 },
  { title: "Research Scientist", count: 60780 },

  // Product & Project Management
  { title: "Product Manager", count: 86240 },
  { title: "Senior Product Manager", count: 68420 },
  { title: "Associate Product Manager", count: 64180 },
  { title: "Product Owner", count: 72460 },
  { title: "Product Designer", count: 73260 },
  { title: "Project Manager", count: 104280 },
  { title: "Senior Project Manager", count: 74820 },
  { title: "Junior Project Manager", count: 63240 },
  { title: "Program Manager", count: 71480 },
  { title: "Program Coordinator", count: 64120 },
  { title: "Scrum Master", count: 68460 },
  { title: "Agile Coach", count: 61420 },
  { title: "Project Coordinator", count: 67240 },
  { title: "Operations Project Manager", count: 62840 },
  { title: "Technical Project Manager", count: 65180 },
  { title: "Product Operations Manager", count: 60740 },

  // Design & Creative
  { title: "Graphic Designer", count: 82340 },
  { title: "Senior Graphic Designer", count: 67480 },
  { title: "UI Designer", count: 64120 },
  { title: "UX Designer", count: 67890 },
  { title: "UI/UX Designer", count: 72840 },
  { title: "UX Researcher", count: 61480 },
  { title: "Visual Designer", count: 63240 },
  { title: "Interaction Designer", count: 60720 },
  { title: "Brand Designer", count: 61840 },
  { title: "Product Designer", count: 73260 },
  { title: "Web Designer", count: 78420 },
  { title: "Motion Designer", count: 62480 },
  { title: "Motion Graphics Designer", count: 61340 },
  { title: "Art Director", count: 64180 },
  { title: "Creative Director", count: 68740 },
  { title: "Creative Designer", count: 69420 },
  { title: "Illustrator", count: 61260 },
  { title: "Animator", count: 60480 },
  { title: "Video Editor", count: 78320 },
  { title: "Video Producer", count: 62480 },
  { title: "Photographer", count: 71840 },
  { title: "3D Artist", count: 60420 },
  { title: "3D Designer", count: 61180 },

  // Marketing
  { title: "Marketing Specialist", count: 84620 },
  { title: "Marketing Manager", count: 92480 },
  { title: "Marketing Coordinator", count: 71840 },
  { title: "Digital Marketing Specialist", count: 72840 },
  { title: "Digital Marketing Manager", count: 64280 },
  { title: "Digital Marketing Coordinator", count: 61420 },
  { title: "SEO Specialist", count: 69480 },
  { title: "SEO Manager", count: 61840 },
  { title: "SEM Specialist", count: 60480 },
  { title: "Content Marketing Specialist", count: 67240 },
  { title: "Content Marketing Manager", count: 62840 },
  { title: "Social Media Manager", count: 68940 },
  { title: "Social Media Specialist", count: 72480 },
  { title: "Social Media Coordinator", count: 61420 },
  { title: "Email Marketing Specialist", count: 64280 },
  { title: "Growth Marketing Manager", count: 61840 },
  { title: "Growth Marketing Specialist", count: 60420 },
  { title: "Brand Manager", count: 67820 },
  { title: "Brand Strategist", count: 61340 },
  { title: "Marketing Analyst", count: 64180 },
  { title: "Market Research Analyst", count: 74620 },
  { title: "Public Relations Specialist", count: 68420 },
  { title: "Public Relations Manager", count: 63240 },
  { title: "Communications Specialist", count: 72180 },
  { title: "Communications Manager", count: 61480 },

  // Writing & Content
  { title: "Content Writer", count: 75260 },
  { title: "Technical Writer", count: 61380 },
  { title: "Copywriter", count: 68420 },
  { title: "Senior Copywriter", count: 62140 },
  { title: "SEO Content Writer", count: 64780 },
  { title: "Content Editor", count: 67240 },
  { title: "Managing Editor", count: 61480 },
  { title: "Editor", count: 71840 },
  { title: "Proofreader", count: 62820 },
  { title: "Blogger", count: 60480 },
  { title: "Content Strategist", count: 64180 },
  { title: "Technical Content Writer", count: 60840 },
  { title: "Grant Writer", count: 60420 },
  { title: "Proposal Writer", count: 61780 },

  // Sales
  { title: "Sales Representative", count: 121640 },
  { title: "Sales Associate", count: 98740 },
  { title: "Sales Executive", count: 91820 },
  { title: "Sales Manager", count: 68970 },
  { title: "Senior Sales Manager", count: 64280 },
  { title: "Sales Coordinator", count: 72460 },
  { title: "Sales Consultant", count: 81240 },
  { title: "Business Development Representative", count: 78420 },
  { title: "Business Development Manager", count: 74860 },
  { title: "Business Development Executive", count: 68240 },
  { title: "Account Executive", count: 86240 },
  { title: "Account Manager", count: 79840 },
  { title: "Key Account Manager", count: 64180 },
  { title: "Inside Sales Representative", count: 73480 },
  { title: "Outside Sales Representative", count: 67420 },
  { title: "Sales Operations Analyst", count: 61340 },
  { title: "Sales Operations Manager", count: 62480 },
  { title: "Sales Development Representative", count: 69240 },
  { title: "Telemarketer", count: 61780 },

  // Customer Service
  { title: "Customer Service Representative", count: 114820 },
  { title: "Customer Support Specialist", count: 114820 },
  { title: "Customer Support Agent", count: 97860 },
  { title: "Customer Service Agent", count: 102480 },
  { title: "Customer Success Manager", count: 76240 },
  { title: "Customer Success Specialist", count: 69480 },
  { title: "Customer Experience Specialist", count: 67240 },
  { title: "Customer Experience Manager", count: 61480 },
  { title: "Call Center Representative", count: 93620 },
  { title: "Call Center Agent", count: 88420 },
  { title: "Contact Center Representative", count: 73480 },
  { title: "Technical Support Representative", count: 69240 },
  { title: "Client Services Representative", count: 71840 },
  { title: "Client Success Manager", count: 64180 },

  // Administrative & Virtual Work
  { title: "Virtual Assistant", count: 86420 },
  { title: "Executive Assistant", count: 79240 },
  { title: "Administrative Assistant", count: 80350 },
  { title: "Administrative Coordinator", count: 72480 },
  { title: "Office Assistant", count: 74820 },
  { title: "Office Manager", count: 68420 },
  { title: "Receptionist", count: 91840 },
  { title: "Data Entry Specialist", count: 93420 },
  { title: "Data Entry Clerk", count: 78260 },
  { title: "Data Entry Operator", count: 74620 },
  { title: "Administrative Specialist", count: 67840 },
  { title: "Operations Assistant", count: 71480 },
  { title: "Personal Assistant", count: 68240 },
  { title: "Scheduling Coordinator", count: 62480 },
  { title: "Records Specialist", count: 60840 },
  { title: "Document Specialist", count: 61420 },

  // Finance & Accounting
  { title: "Accountant", count: 96740 },
  { title: "Senior Accountant", count: 72480 },
  { title: "Junior Accountant", count: 68420 },
  { title: "Accounting Assistant", count: 74860 },
  { title: "Accounting Clerk", count: 72140 },
  { title: "Accounts Payable Specialist", count: 67480 },
  { title: "Accounts Receivable Specialist", count: 68240 },
  { title: "Financial Analyst", count: 81240 },
  { title: "Senior Financial Analyst", count: 64180 },
  { title: "Finance Manager", count: 69420 },
  { title: "Finance Specialist", count: 62840 },
  { title: "Payroll Specialist", count: 67240 },
  { title: "Payroll Manager", count: 61480 },
  { title: "Bookkeeper", count: 83420 },
  { title: "Billing Specialist", count: 64820 },
  { title: "Billing Coordinator", count: 61240 },
  { title: "Credit Analyst", count: 62840 },
  { title: "Financial Controller", count: 60780 },
  { title: "Treasury Analyst", count: 60420 },
  { title: "Tax Accountant", count: 61840 },
  { title: "Auditor", count: 68240 },
  { title: "Internal Auditor", count: 62480 },

  // Human Resources & Recruiting
  { title: "Human Resources Specialist", count: 70480 },
  { title: "Human Resources Manager", count: 74620 },
  { title: "HR Coordinator", count: 68240 },
  { title: "HR Generalist", count: 71840 },
  { title: "HR Assistant", count: 67480 },
  { title: "HR Business Partner", count: 63240 },
  { title: "Recruiter", count: 78360 },
  { title: "Technical Recruiter", count: 67420 },
  { title: "Recruiting Coordinator", count: 64820 },
  { title: "Talent Acquisition Specialist", count: 72840 },
  { title: "Talent Acquisition Manager", count: 61480 },
  { title: "Talent Manager", count: 60840 },
  { title: "Training Coordinator", count: 61780 },
  { title: "Learning and Development Specialist", count: 60420 },
  { title: "Compensation Analyst", count: 60280 },

  // Operations & Management
  { title: "Operations Manager", count: 66740 },
  { title: "Operations Coordinator", count: 72480 },
  { title: "Operations Specialist", count: 69420 },
  { title: "Operations Analyst", count: 68140 },
  { title: "Business Operations Manager", count: 64820 },
  { title: "Business Analyst", count: 74680 },
  { title: "Business Operations Analyst", count: 62480 },
  { title: "General Manager", count: 67420 },
  { title: "Regional Manager", count: 61840 },
  { title: "Branch Manager", count: 68240 },
  { title: "Store Manager", count: 84620 },
  { title: "Assistant Manager", count: 79240 },
  { title: "Operations Director", count: 60780 },
  { title: "Process Improvement Specialist", count: 61240 },
  { title: "Process Analyst", count: 62180 },

  // Supply Chain & Logistics
  { title: "Supply Chain Analyst", count: 64820 },
  { title: "Supply Chain Manager", count: 68240 },
  { title: "Supply Chain Specialist", count: 62480 },
  { title: "Logistics Coordinator", count: 74820 },
  { title: "Logistics Manager", count: 67240 },
  { title: "Logistics Specialist", count: 64180 },
  { title: "Procurement Specialist", count: 68420 },
  { title: "Procurement Manager", count: 62140 },
  { title: "Purchasing Specialist", count: 73480 },
  { title: "Purchasing Manager", count: 61480 },
  { title: "Inventory Specialist", count: 62840 },
  { title: "Inventory Manager", count: 60780 },
  { title: "Warehouse Associate", count: 82460 },
  { title: "Warehouse Manager", count: 67420 },
  { title: "Warehouse Supervisor", count: 71840 },
  { title: "Distribution Manager", count: 60480 },
  { title: "Supply Chain Coordinator", count: 61240 },

  // Healthcare
  { title: "Registered Nurse", count: 118640 },
  { title: "Nurse Practitioner", count: 82420 },
  { title: "Licensed Practical Nurse", count: 74680 },
  { title: "Clinical Nurse", count: 68420 },
  { title: "Medical Assistant", count: 91840 },
  { title: "Medical Receptionist", count: 72480 },
  { title: "Medical Billing Specialist", count: 68240 },
  { title: "Medical Coder", count: 71480 },
  { title: "Healthcare Administrator", count: 64820 },
  { title: "Healthcare Coordinator", count: 62740 },
  { title: "Pharmacy Technician", count: 78240 },
  { title: "Dental Assistant", count: 69480 },
  { title: "Dental Hygienist", count: 62480 },
  { title: "Radiologic Technologist", count: 61420 },
  { title: "Physical Therapist", count: 67840 },
  { title: "Occupational Therapist", count: 61280 },
  { title: "Care Coordinator", count: 64820 },
  { title: "Patient Care Coordinator", count: 63480 },

  // Education
  { title: "Teacher", count: 112480 },
  { title: "Elementary School Teacher", count: 82460 },
  { title: "High School Teacher", count: 78640 },
  { title: "English Teacher", count: 91820 },
  { title: "Math Teacher", count: 72480 },
  { title: "Science Teacher", count: 68420 },
  { title: "Special Education Teacher", count: 64180 },
  { title: "Teaching Assistant", count: 76240 },
  { title: "Teacher Assistant", count: 71840 },
  { title: "Tutor", count: 94620 },
  { title: "Online Tutor", count: 72480 },
  { title: "Academic Advisor", count: 61420 },
  { title: "Instructional Designer", count: 64280 },
  { title: "Curriculum Developer", count: 60480 },
  { title: "Education Coordinator", count: 61240 },

  // Engineering
  { title: "Mechanical Engineer", count: 82460 },
  { title: "Electrical Engineer", count: 79820 },
  { title: "Civil Engineer", count: 84640 },
  { title: "Chemical Engineer", count: 64280 },
  { title: "Industrial Engineer", count: 67420 },
  { title: "Manufacturing Engineer", count: 64820 },
  { title: "Quality Engineer", count: 68240 },
  { title: "Process Engineer", count: 69420 },
  { title: "Project Engineer", count: 72840 },
  { title: "Design Engineer", count: 67480 },
  { title: "Environmental Engineer", count: 61420 },
  { title: "Biomedical Engineer", count: 60840 },
  { title: "Aerospace Engineer", count: 60480 },
  { title: "Engineering Manager", count: 64820 },
  { title: "Engineering Technician", count: 71840 },

  // Legal
  { title: "Attorney", count: 68420 },
  { title: "Lawyer", count: 74680 },
  { title: "Associate Attorney", count: 62480 },
  { title: "Legal Assistant", count: 78240 },
  { title: "Legal Secretary", count: 67420 },
  { title: "Paralegal", count: 82460 },
  { title: "Legal Analyst", count: 61480 },
  { title: "Compliance Analyst", count: 64820 },
  { title: "Compliance Specialist", count: 67240 },
  { title: "Compliance Manager", count: 60480 },
  { title: "Contract Specialist", count: 61840 },
  { title: "Contract Manager", count: 60780 },

  // Real Estate
  { title: "Real Estate Agent", count: 92840 },
  { title: "Real Estate Broker", count: 67420 },
  { title: "Property Manager", count: 74820 },
  { title: "Property Administrator", count: 62480 },
  { title: "Leasing Consultant", count: 68240 },
  { title: "Real Estate Analyst", count: 61420 },
  { title: "Real Estate Manager", count: 60840 },

  // Hospitality & Retail
  { title: "Hotel Manager", count: 68420 },
  { title: "Front Desk Agent", count: 82460 },
  { title: "Hotel Receptionist", count: 74820 },
  { title: "Guest Services Representative", count: 69240 },
  { title: "Restaurant Manager", count: 71840 },
  { title: "Restaurant Supervisor", count: 67420 },
  { title: "Restaurant Server", count: 96840 },
  { title: "Bartender", count: 82460 },
  { title: "Chef", count: 78420 },
  { title: "Sous Chef", count: 64820 },
  { title: "Cook", count: 102480 },
  { title: "Retail Sales Associate", count: 112640 },
  { title: "Retail Manager", count: 78420 },
  { title: "Retail Supervisor", count: 71840 },
  { title: "Store Associate", count: 93420 },
  { title: "Cashier", count: 108240 },
  { title: "Merchandiser", count: 68420 },

  // Media & Communications
  { title: "Journalist", count: 67480 },
  { title: "Reporter", count: 62840 },
  { title: "News Editor", count: 61420 },
  { title: "Producer", count: 64280 },
  { title: "Broadcast Producer", count: 60840 },
  { title: "Content Producer", count: 67420 },
  { title: "Podcast Producer", count: 60480 },
  { title: "Communications Specialist", count: 72180 },
  { title: "Communications Manager", count: 61480 },
  { title: "Media Planner", count: 60840 },
  { title: "Media Buyer", count: 62140 },

  // Insurance
  { title: "Insurance Agent", count: 82460 },
  { title: "Insurance Sales Agent", count: 74820 },
  { title: "Insurance Underwriter", count: 68240 },
  { title: "Claims Adjuster", count: 71840 },
  { title: "Claims Specialist", count: 67420 },
  { title: "Insurance Analyst", count: 61480 },
  { title: "Insurance Coordinator", count: 60840 },

  // Banking & Financial Services
  { title: "Bank Teller", count: 84620 },
  { title: "Personal Banker", count: 78420 },
  { title: "Relationship Manager", count: 72480 },
  { title: "Loan Officer", count: 74820 },
  { title: "Credit Analyst", count: 62840 },
  { title: "Mortgage Loan Officer", count: 61480 },
  { title: "Risk Analyst", count: 67240 },
  { title: "Risk Manager", count: 61840 },
  { title: "Investment Analyst", count: 64280 },
  { title: "Investment Manager", count: 60780 },
  { title: "Wealth Manager", count: 60480 },
  { title: "Financial Advisor", count: 82460 },

  // Science & Research
  { title: "Research Analyst", count: 71840 },
  { title: "Research Associate", count: 68240 },
  { title: "Research Assistant", count: 74820 },
  { title: "Research Coordinator", count: 61480 },
  { title: "Laboratory Technician", count: 72480 },
  { title: "Lab Technician", count: 68420 },
  { title: "Laboratory Manager", count: 60840 },
  { title: "Clinical Research Associate", count: 62480 },
  { title: "Clinical Research Coordinator", count: 61840 },

  // Other Common Roles
  { title: "Security Officer", count: 94620 },
  { title: "Security Guard", count: 112840 },
  { title: "Driver", count: 108420 },
  { title: "Delivery Driver", count: 102680 },
  { title: "Truck Driver", count: 98420 },
  { title: "Courier", count: 84620 },
  { title: "Maintenance Technician", count: 78420 },
  { title: "Maintenance Manager", count: 62840 },
  { title: "Electrician", count: 91840 },
  { title: "Plumber", count: 84620 },
  { title: "Construction Manager", count: 67240 },
  { title: "Construction Worker", count: 98420 },
  { title: "Site Supervisor", count: 72480 },
  { title: "Field Technician", count: 68240 },
  { title: "Field Service Technician", count: 64820 },
  { title: "Customer Service Manager", count: 67480 },
  { title: "General Laborer", count: 92640 },
  { title: "Production Supervisor", count: 68420 },
  { title: "Production Manager", count: 64820 },
  { title: "Quality Assurance Specialist", count: 72480 },
  { title: "Quality Control Specialist", count: 67420 }
];
